prefix ?= /usr
USE_FLTK2 = 1
USE_NCURSES = 1
BUILD_EDITOR = 1
#INSTALL_DEV is not set
#STATIC is not set
CPPFLAGS += -D '_USE_FLTK2_ = 1'
CPPFLAGS += -D '_USE_NCURSES_ = 1'
CPPFLAGS += -D '_BUILD_EDITOR_ = 1'
######## THERE IS NO SERVICABLE PARTS BELOW THIS LINE ########

WD = $(shell pwd)

INSTALL = cp -d

DESTIR=
PREFIX ?= $(DESTDIR)$(prefix)

CC = gcc  -Wall --pedantic-errors -Wstrict-prototypes
CXX = g++  -Wall --pedantic-errors
AR=ar rcs

CCOPTIMISATION += -O3 -funroll-loops -mtune=i686 -march=i486

CPPFLAGS += -D 'APPLICATION_VERSION="$(NAME) $(MAJOR).$(MINOR).$(REVISION)"' -D 'LEVELSETS_PATH="$(LEVELSETS_DIR)"'

ifdef USE_FLTK2
	CPPFLAGS += -D 'THEMES_PATH="$(THEMES_DIR)"'
else
ifdef BUILD_EDITOR
	CPPFLAGS += -D 'THEMES_PATH="$(THEMES_DIR)"'
endif
endif

NAME = ngstar
MAJOR = 2
MINOR = 1
REVISION = 9

LEVELSETS_DIR = $(PREFIX)/share/$(NAME)/levelsets
THEMES_DIR = $(PREFIX)/share/$(NAME)/themes
BIN_DIR = $(PREFIX)/bin
DOC_DIR = $(PREFIX)/doc/$(NAME)-$(MAJOR).$(MINOR).$(REVISION)
LIB_DIR = $(PREFIX)/lib
INCLUDES_DIR = $(PREFIX)/include/ngstar2

.PHONY : clean real-clean install uninstall all archive archive_src archive_bin_dynamic archive_bin_static

.cc.o:
	echo Compiling $<...
	$(CXX) -I.. $(CPPFLAGS) -c $<

# Be quiet when building...
.SILENT:

